name: cicd with terraform

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  ECR: 030635937630.dkr.ecr.ap-south-1.amazonaws.com

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: install dep
        run: |
          cd frontend
          npm ci
          npm run lint

      - name: lint for backend
        run: |
          cd backend
          npm ci
          npm run lint


  scan:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: scan for frontend
        run: |
          cd frontend
          npm ci
          npm audit --audit-level=critical || true

      - name: scan for backend
        run: |
          cd backend
          npm ci
          npm audit --audit-level=high || true

  build:
    runs-on: ubuntu-latest
    needs: [lint, scan]
    outputs:
      image_tag: ${{ steps.tag.outputs.image_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # This step determines if we are on dev or main and sets an environment variable
      - name: Set Environment Variables
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "ENV_TAG=prod" >> $GITHUB_ENV
          else
            echo "ENV_TAG=dev" >> $GITHUB_ENV
          fi

      - name: AWS Login
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::030635937630:role/github-actions-role
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Images
        run: |
          SHA=${{ github.sha }}
          docker build -t $ECR/${{ env.ENV_TAG }}-frontend:$SHA -t $ECR/${{ env.ENV_TAG }}-frontend:latest ./frontend
          docker push $ECR/${{ env.ENV_TAG }}-frontend:$SHA
          docker push $ECR/${{ env.ENV_TAG }}-frontend:latest

          docker build -t $ECR/${{ env.ENV_TAG }}-backend:$SHA -t $ECR/${{ env.ENV_TAG }}-backend:latest ./backend
          docker push $ECR/${{ env.ENV_TAG }}-backend:$SHA
          docker push $ECR/${{ env.ENV_TAG }}-backend:latest

      - name: export image tag
        id: tag
        run: echo "image_tag=${{ github.sha }}" >> $GITHUB_OUTPUT


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set Deploy Environment Variables
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "ENV_TAG=prod" >> $GITHUB_ENV
          else
            echo "ENV_TAG=dev" >> $GITHUB_ENV
          fi

      - name: Setup AWS Credentials for Terraform
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::030635937630:role/github-actions-role
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v4

      - name: terraform init
        run: terraform init

      - name: terraform validate
        run: terraform validate

      - name: terraform plan
        run: |
          terraform plan -no-color \
            -var-file="${{ env.ENV_TAG }}.tfvars" \
            -var "image_tag=${{ needs.build.outputs.image_tag }}"

      - name: terraform apply
        run: |
          terraform apply -auto-approve \
            -var-file="${{ env.ENV_TAG }}.tfvars" \
            -var "image_tag=${{ needs.build.outputs.image_tag }}"

      - name: force ECS redeployment
        run: |
          aws ecs update-service \
            --cluster ${{ env.ENV_TAG }}-cluster \
            --service ${{ env.ENV_TAG }}-service \
            --force-new-deployment \
            --region ap-south-1



  
